name = "podmander"
description = "Container orchestration for small multi-node deployments"
version = "0.1.0-dev"
authors = ["Jochen Lillich"]
maintainers = ["Jochen Lillich <contact@geewiz.dev>"]
maintainers-logins = ["geewiz"]
licenses = "Apache-2.0"

[[depends-on]]
czmq_ada = "~0.5.0"
aunit = "~26.0.0"
spoon = "~1.0.1"
ada_sqlite3 = "~0.1.1"

[build-switches]
"*".style_checks = "yes"
"*".ada_version = "ada2022"

[[actions]]
type = "test"
command = ["scripts/run_tests.sh"]

