name = "podmander"
description = "Container orchestration for small multi-node deployments"
version = "0.2.4"
authors = ["Jochen Lillich"]
maintainers = ["Jochen Lillich <contact@geewiz.dev>"]
maintainers-logins = ["geewiz"]
licenses = "Apache-2.0"
project-files = ["podmander.gpr", "podctl.gpr", "podmander_tests.gpr"]

[[depends-on]]
czmq_ada = "~0.5.0"
aunit = "~26.0.0"
spoon = "~1.0.1"
ada_sqlite3 = "~0.1.1"

[build-switches]
"*".style_checks = "yes"
"*".ada_version = "ada2022"

[[depends-on]]
ada_toml = "~0.5.0"
gnatcoll = "~26.0.0"

[[depends-on]]
clic = "~0.3.0"

[[pins]]
# geewiz/clic tag v0.3.0-ada-toml-0.5 - broadens ada_toml compat to ~0.5
clic.url = "https://github.com/geewiz/clic.git"
clic.commit = "093fc3eba900bf56228547377c5e3f6f6f73d622"
